#!/bin/sh
# Resolve the symlink to get the actual path to the script
SCRIPT_PATH=$(readlink -f "$0")

# Get the directory from the resolved script path
SCRIPT_DIR=$(dirname "$SCRIPT_PATH")

$SCRIPT_DIR/.virtualenv/bin/python "$SCRIPT_DIR/cbrtools.py" "$@"