[package]
name = "metal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "metal"
crate-type = ["cdylib"]

[dependencies]
pdbtbx = "0.11.0"
polars = "0.37.0"
pyo3 = "0.20.2"
